spring:
  application:
    name: front-service
logging:
  level:
    root: INFO
server:
  port: 51586
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
      fetchRegistry: false