server:
  port: 8189
  servlet:
    context-path: /app
utils:
  cart:
    prefix: SPRING_WEB_
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://192.168.99.101:5432/postgres

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        ddl-auto: update

    show-sql: true
    generate-ddl: true
    database: postgresql
